# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U-y6oZVP4epSMqX3nCWcGa4t93PS1wfd
"""

!pip install geopandas openpyxl -q

import geopandas as gpd
import pandas as pd
import os

# ============================================================
# 1. FILE NAMES
# ============================================================

wards_file = "/content/Hamilton_Parks_&_Sports_Facilities/Ward_Boundaries.geojson"
parks_file = "/content/Hamilton_Parks_&_Sports_Facilities/Parks.geojson"
sports_file = "/content/Hamilton_Parks_&_Sports_Facilities/Park_Sports_Fields.geojson"


# ============================================================
# 2. READ THE THREE DATASETS
# ============================================================

wards = gpd.read_file(wards_file)
parks = gpd.read_file(parks_file)
sports = gpd.read_file(sports_file)

print("Loaded data:")
print(f"Wards:         {len(wards)}")
print(f"Parks:         {len(parks)}")
print(f"Sports fields: {len(sports)}")


# ============================================================
# 3. CHECK REQUIRED FIELDS
# ============================================================

print("\nWard fields:")
print(list(wards.columns))

print("\nPark fields:")
print(list(parks.columns))

print("\nSports field fields:")
print(list(sports.columns))


# ============================================================
# 4. MAKE ALL LAYERS USE THE SAME CRS
# ============================================================

parks = parks.to_crs(wards.crs)
sports = sports.to_crs(wards.crs)


# ============================================================
# 5. ASSIGN EACH PARK TO A WARD
# ============================================================
#
# We use the park centroid.
# This means each park belongs to exactly ONE ward.
#

parks_with_wards = parks.copy()

# Create centroid
parks_with_wards["park_centroid"] = parks_with_wards.geometry.centroid

# Temporarily use centroid as geometry for spatial join
park_points = parks_with_wards.copy()
park_points = park_points.set_geometry("park_centroid")

# Spatial join
park_join = gpd.sjoin(
    park_points,
    wards[["WARD", "geometry"]],
    how="left",
    predicate="within"
)

# Transfer WARD back to the original park polygon
parks_with_wards["WARD"] = park_join["WARD"].values


# ============================================================
# 6. IDENTIFY SPORTS PARKS
# ============================================================
#
# Your Parks layer has a TYPE field.
# We look for "Sports Park" in TYPE.
#

parks_with_wards["IS_SPORTS_PARK"] = (
    parks_with_wards["TYPE"]
    .fillna("")
    .str.contains(
        "Sports",
        case=False,
        na=False
    )
)

print("\nSports parks identified:")
print(
    parks_with_wards["IS_SPORTS_PARK"]
    .value_counts()
)


# ============================================================
# 7. ASSIGN EACH SPORTS FIELD TO A WARD
# ============================================================

sports_with_wards = sports.copy()

sports_join = gpd.sjoin(
    sports_with_wards,
    wards[["WARD", "geometry"]],
    how="left",
    predicate="within"
)

sports_with_wards["WARD"] = sports_join["WARD"].values


# ============================================================
# 8. COUNT TOTAL PARKS BY WARD
# ============================================================

parks_by_ward = (
    parks_with_wards
    .dropna(subset=["WARD"])
    .groupby("WARD")
    .size()
    .reset_index(name="TOTAL_PARKS")
)


# ============================================================
# 9. COUNT SPORTS PARKS BY WARD
# ============================================================

sports_parks_by_ward = (
    parks_with_wards[
        parks_with_wards["IS_SPORTS_PARK"] == True
    ]
    .dropna(subset=["WARD"])
    .groupby("WARD")
    .size()
    .reset_index(name="SPORTS_PARKS")
)


# ============================================================
# 10. COUNT SPORTS FIELDS BY WARD
# ============================================================

sports_fields_by_ward = (
    sports_with_wards
    .dropna(subset=["WARD"])
    .groupby("WARD")
    .size()
    .reset_index(name="SPORTS_FIELDS")
)


# ============================================================
# 11. CREATE WARD SUMMARY
# ============================================================

wards_summary = wards.copy()

# Keep only useful ward information
wards_summary = wards_summary[
    [
        "WARD",
        "COUNCILLOR_NAME",
        "geometry"
    ]
].copy()


# Add park counts
wards_summary = wards_summary.merge(
    parks_by_ward,
    on="WARD",
    how="left"
)


# Add sports park counts
wards_summary = wards_summary.merge(
    sports_parks_by_ward,
    on="WARD",
    how="left"
)


# Add sports field counts
wards_summary = wards_summary.merge(
    sports_fields_by_ward,
    on="WARD",
    how="left"
)


# Replace missing counts with zero
count_columns = [
    "TOTAL_PARKS",
    "SPORTS_PARKS",
    "SPORTS_FIELDS"
]

wards_summary[count_columns] = (
    wards_summary[count_columns]
    .fillna(0)
    .astype(int)
)


# ============================================================
# 12. CALCULATE SPORTS FIELDS PER PARK
# ============================================================

wards_summary["SPORTS_FIELDS_PER_PARK"] = (
    wards_summary["SPORTS_FIELDS"]
    / wards_summary["TOTAL_PARKS"].replace(0, pd.NA)
).round(2)

wards_summary["SPORTS_FIELDS_PER_PARK"] = (
    wards_summary["SPORTS_FIELDS_PER_PARK"]
    .fillna(0)
)


# ============================================================
# 13. SORT WARDS
# ============================================================

wards_summary["WARD_SORT"] = (
    wards_summary["WARD"]
    .astype(str)
    .astype(int)
)

wards_summary = (
    wards_summary
    .sort_values("WARD_SORT")
    .drop(columns=["WARD_SORT"])
    .reset_index(drop=True)
)


# ============================================================
# 14. DISPLAY SUMMARY TABLE
# ============================================================

print("\n======================================")
print("HAMILTON RECREATION SUMMARY BY WARD")
print("======================================\n")

display(
    wards_summary[
        [
            "WARD",
            "TOTAL_PARKS",
            "SPORTS_PARKS",
            "SPORTS_FIELDS",
            "SPORTS_FIELDS_PER_PARK"
        ]
    ]
)


# ============================================================
# 15. CREATE OUTPUT FOLDER
# ============================================================

output_folder = "/content/hamilton_gis_outputs"

os.makedirs(
    output_folder,
    exist_ok=True
)


# ============================================================
# 16. SAVE WARD SUMMARY AS GEOJSON
# ============================================================

wards_summary_file = (
    output_folder +
    "/wards_summary.geojson"
)

wards_summary.to_file(
    wards_summary_file,
    driver="GeoJSON"
)


# ============================================================
# 17. SAVE PARKS WITH WARD FIELD
# ============================================================

parks_output = (
    output_folder +
    "/parks_with_wards.geojson"
)

# Remove temporary centroid column
parks_export = parks_with_wards.drop(
    columns=["park_centroid"],
    errors="ignore"
)

parks_export.to_file(
    parks_output,
    driver="GeoJSON"
)


# ============================================================
# 18. SAVE SPORTS FIELDS WITH WARD FIELD
# ============================================================

sports_output = (
    output_folder +
    "/sports_fields_with_wards.geojson"
)

sports_with_wards.to_file(
    sports_output,
    driver="GeoJSON"
)


# ============================================================
# 19. CREATE SIMPLE EXCEL SUMMARY
# ============================================================

summary_table = wards_summary[
    [
        "WARD",
        "TOTAL_PARKS",
        "SPORTS_PARKS",
        "SPORTS_FIELDS",
        "SPORTS_FIELDS_PER_PARK"
    ]
].copy()


excel_file = (
    output_folder +
    "/hamilton_ward_recreation_summary.xlsx"
)

summary_table.to_excel(
    excel_file,
    index=False
)


# ============================================================
# 20. CREATE CSV SUMMARY
# ============================================================

csv_file = (
    output_folder +
    "/hamilton_ward_recreation_summary.csv"
)

summary_table.to_csv(
    csv_file,
    index=False
)


# ============================================================
# 21. PRINT OUTPUT FILES
# ============================================================

print("\n======================================")
print("FILES CREATED")
print("======================================")

print("\n1. Ward summary:")
print(wards_summary_file)

print("\n2. Parks with ward:")
print(parks_output)

print("\n3. Sports fields with ward:")
print(sports_output)

print("\n4. Excel summary:")
print(excel_file)

print("\n5. CSV summary:")
print(csv_file)

print("\nDone!")